spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: abn-registry
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
